[WARNING][2018-06-29 09:59:12,302][Thread-7:1212][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-06-29 10:05:56,030][Thread-19:4576][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-06-29 10:39:31,553][Thread-8:2444][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[ERROR][2018-06-29 17:46:47,405][Thread-1:12416][task_id:django.request][exception.py:135][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MyPythonProject\MSS\StreamSystem\class_based_views.py", line 29, in index
    return render(request, 'index.html')
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
[ERROR][2018-06-29 17:54:09,252][Thread-5:8468][task_id:django.request][exception.py:135][Internal Server Error: /stream/add/]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\MyPythonProject\MSS\StreamSystem\class_based_views.py", line 62, in post
    return self.json_response(reply)
  File "D:\MyPythonProject\MSS\StreamSystem\class_based_views.py", line 25, in json_response
    return HttpResponse(json.dumps(content))
  File "D:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "D:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "D:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <StreamSystem.StreamFunc.StartStreamMixin object at 0x034D94F0> is not JSON serializable
[WARNING][2018-07-02 10:52:33,678][Thread-7:8188][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[ERROR][2018-07-02 10:53:10,229][Thread-18:4952][task_id:django.request][exception.py:135][Internal Server Error: /stream/add/]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\MyPythonProject\MSS\StreamSystem\class_based_views.py", line 62, in post
    return self.json_response(reply)
  File "D:\MyPythonProject\MSS\StreamSystem\class_based_views.py", line 25, in json_response
    return HttpResponse(json.dumps(content))
  File "D:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "D:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "D:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <StreamSystem.StreamFunc.StartStreamMixin object at 0x038B8B70> is not JSON serializable
[ERROR][2018-07-02 11:00:35,732][Thread-1:10044][task_id:django.request][exception.py:135][Internal Server Error: /stream/add/]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\utils\deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "D:\Python27\lib\site-packages\django\middleware\clickjacking.py", line 32, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'unicode' object has no attribute 'get'
[ERROR][2018-07-02 11:01:19,868][Thread-14:8352][task_id:django.request][exception.py:135][Internal Server Error: /stream/add/]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\utils\deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "D:\Python27\lib\site-packages\django\middleware\clickjacking.py", line 32, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'unicode' object has no attribute 'get'
[ERROR][2018-07-02 11:05:24,161][Thread-1:6540][task_id:django.request][exception.py:135][Internal Server Error: /stream/add/]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\utils\deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "D:\Python27\lib\site-packages\django\middleware\common.py", line 115, in process_response
    if response.status_code == 404:
AttributeError: 'dict' object has no attribute 'status_code'
[ERROR][2018-07-02 11:07:36,233][Thread-8:8912][task_id:django.request][exception.py:135][Internal Server Error: /stream/add/]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\utils\deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "D:\Python27\lib\site-packages\django\middleware\common.py", line 115, in process_response
    if response.status_code == 404:
AttributeError: 'dict' object has no attribute 'status_code'
[WARNING][2018-07-02 13:44:11,536][Thread-13:13108][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 14:57:13,200][Thread-83:12444][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 14:57:57,045][Thread-91:1324][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 14:59:47,829][Thread-99:13736][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 15:00:23,970][Thread-107:13316][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 15:00:37,505][Thread-115:13508][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 15:05:46,983][Thread-123:13188][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 15:09:49,176][Thread-147:10900][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 15:18:25,128][Thread-165:13100][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 15:18:32,591][Thread-173:12488][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 15:18:50,822][Thread-181:7256][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 15:25:23,186][Thread-206:9416][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 15:26:05,302][Thread-214:7916][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 15:57:51,740][Thread-229:6016][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 15:59:28,769][Thread-237:14784][task_id:django.request][base.py:152][Not Found: /favicon.ico]
[WARNING][2018-07-02 16:01:54,012][Thread-245:1740][task_id:django.request][base.py:152][Not Found: /favicon.ico]
